# Imagine Education AWS
# Cloud Front d2d5v59d5ikv3b.cloudfront.net
# S3 Bucket ko_videos
development:
  bucket: "imagine_co_videos"
  access_key_id: "AKIAJ6ZUFAQZG55JAHBQ"
  secret_access_key: "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"
  
test:
  bucket: "imagine_co_videos"
  access_key_id: "AKIAJ6ZUFAQZG55JAHBQ"
  secret_access_key: "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"
  
production:
  bucket: "imagine_co_videos"
  access_key_id: "AKIAJ6ZUFAQZG55JAHBQ"
  secret_access_key: "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"